FROM python:3.12-slim

WORKDIR /app

# 必要なビルドツールとヘッダーをインストール
RUN apt-get update && apt-get install -y \
    build-essential \
    python3-dev \
    gcc \
    netcat-openbsd \
    && rm -rf /var/lib/apt/lists/*

COPY app/requirements.txt .
RUN pip install --no-cache-dir  -r requirements.txt

COPY app .

COPY Docker/app/entrypoint.dev.sh /usr/local/bin/entrypoint.sh
RUN chmod +x /usr/local/bin/entrypoint.sh

EXPOSE 8000

ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]